services:
  db:
    image: mysql:9.0.1
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: interview
      MYSQL_DATABASE: interview
      MYSQL_USER: interview
      MYSQL_PASSWORD: interview-pass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    healthcheck:
      test: 'exit 0'
    networks:
      - local_net

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: deploy/tools/docker/backend/Dockerfile
    image: interview-backend
    entrypoint: /backend/entrypoint.sh
    env_file:
      - deploy/tools/env/backend.dev.env
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./deploy/backend/node_modules:/backend/node_modules
      - ./deploy/backend/src:/backend/src
      - ./deploy/backend/migrations:/backend/migrations
    networks:
      - local_net

volumes:
  db-data: {}

networks:
  local_net:
    driver: bridge
